# Generated by Django 5.2.1 on 2025-06-03 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(help_text='One-to-one relationship with the Auth_User table.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address_line_1', models.CharField(blank=True, help_text="First line of the user's default address.", max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, help_text="Second line of the user's default address.", max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text="City of the user's default address.", max_length=255, null=True)),
                ('state', models.CharField(blank=True, help_text="State of the user's default address.", max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text="Postal code of the user's default address.", max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text="Country of the user's default address.", max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text="User's phone number.", max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text="Path to the user's profile picture file.", null=True, upload_to='profile_pics/$Y/$m/$d')),
            ],
        ),
    ]
