# Generated by Django 5.2.1 on 2025-06-03 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(help_text='The user who owns this cart. (One user, one cart).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cart', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the cart was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the cart was last updated.')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='The quantity of the product in the cart.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the cart item was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the cart item was last updated.')),
                ('cart', models.ForeignKey(help_text='The cart this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart')),
                ('product', models.ForeignKey(help_text='The product in this cart item.', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
