# Generated by Django 5.2.1 on 2025-06-03 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the person placing the order.', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the person placing the order.', max_length=100)),
                ('email', models.EmailField(help_text='Email of the person placing the order.', max_length=255)),
                ('address_line_1', models.CharField(help_text='Shipping address line 1.', max_length=255)),
                ('address_line_2', models.CharField(help_text='Shipping address line 2.', max_length=255)),
                ('city', models.CharField(help_text='Shipping city.', max_length=100)),
                ('state', models.CharField(blank=True, help_text='Shipping state.', max_length=100, null=True)),
                ('postal_code', models.CharField(help_text='Shipping postal code.', max_length=20)),
                ('country', models.CharField(help_text='Shipping country.', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for the order contact.', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the order was last updated.')),
                ('paid', models.BooleanField(default=False, help_text='Indicates if the order has been paid for.')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='The total cost of the order.', max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', help_text="Current status of the order (e.g., 'Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled').", max_length=100)),
                ('user', models.ForeignKey(blank=True, help_text='The user who placed the order. Nullable for guest checkouts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the product at the time of purchase.', max_digits=10)),
                ('quantity', models.PositiveIntegerField(help_text='The quantity of the product in this order item.')),
                ('order', models.ForeignKey(help_text='The order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(help_text='The product included in this order item.', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('order', 'product')},
            },
        ),
    ]
