# Generated by Django 5.2.1 on 2025-06-03 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The name of the product category (e.g., "Electronics", "Books").', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='A URL-friendly unique identifier for the category (e.g., "electronics").', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the category.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the category was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the category was last updated.')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The name of the product.', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='A URL-friendly unique identifier for the product.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the product.', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='The selling price of the product (e.g., 99.99).', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text="Path to the product's image file.", null=True, upload_to='products/%Y/%m/%d')),
                ('stock', models.PositiveIntegerField(help_text='Current quantity of the product in stock.')),
                ('available', models.BooleanField(default=True, help_text='Indicates if the product is currently available for purchase.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the product was last updated.')),
                ('category', models.ForeignKey(help_text='The category the product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['id', 'slug'], name='products_pr_id_a08e3c_idx'), models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx')],
            },
        ),
    ]
